<?php
/**
 * Appointment Booking - Step 2: Schedule & Provider (Feature Component)
 *
 * @param string $role (patient|admin)
 */
$role = $role ?? 'patient';
?>

<div class="w-full">
    <!-- Progress Stepper -->
    <?= featured('appointments', 'components/progress-stepper', [
        'currentStep' => 2,
        'title' => 'Schedule Appointment',
    ]) ?>

    <form id="booking-form-step-2" action="step-3-review.php" method="GET" class="space-y-10">
        <input type="hidden" name="service" value="">
        <input type="hidden" name="date" id="selected-date" value="">

        <div class="grid grid-cols-1 lg:grid-cols-12 gap-8">
            <!-- Left Column: Calendar Widget -->
            <div class="lg:col-span-7 bg-card p-8 rounded-[2rem] border border-border shadow-sm">
                <div class="flex items-center justify-between mb-8">
                    <h3 class="text-xl font-black text-foreground tracking-tight">Select Date</h3>
                    <div class="flex items-center gap-3">
                        <button type="button" id="prev-month"
                            class="size-10 flex items-center justify-center hover:bg-muted rounded-xl transition-all border border-border">
                            <span class="material-symbols-outlined text-2xl">chevron_left</span>
                        </button>
                        <span id="calendar-month-label"
                            class="font-black min-w-[140px] text-center text-sm tracking-tight"></span>
                        <button type="button" id="next-month"
                            class="size-10 flex items-center justify-center hover:bg-muted rounded-xl transition-all border border-border">
                            <span class="material-symbols-outlined text-2xl">chevron_right</span>
                        </button>
                    </div>
                </div>

                <!-- Calendar Grid -->
                <div
                    class="grid grid-cols-7 text-center text-[11px] font-black text-muted-foreground uppercase tracking-[0.2em] mb-6">
                    <div class="py-2">Sun</div>
                    <div class="py-2">Mon</div>
                    <div class="py-2">Tue</div>
                    <div class="py-2">Wed</div>
                    <div class="py-2">Thu</div>
                    <div class="py-2">Fri</div>
                    <div class="py-2">Sat</div>
                </div>

                <div class="grid grid-cols-7 gap-3" id="calendar-days">
                    <!-- Calendar days generated by JS -->
                </div>
            </div>

            <!-- Right Column: Time Slots & Provider -->
            <div class="lg:col-span-5 flex flex-col gap-8">
                <!-- Time Selection -->
                <div class="bg-card p-8 rounded-[2rem] border border-border shadow-sm">
                    <h3 class="text-xl font-black mb-6 flex items-center gap-3 text-foreground tracking-tight">
                        <span class="material-symbols-outlined text-primary text-3xl">schedule</span>
                        Available Slots
                    </h3>
                    <p class="text-sm font-medium text-muted-foreground mb-6 italic">Times for <span
                            id="display-selected-date" class="text-foreground font-black not-italic">Loading...</span>
                    </p>

                    <div id="time-slots-container" class="grid grid-cols-2 gap-4">
                        <!-- Dynamic slots generated by JS -->
                        <div class="col-span-2 text-center text-sm font-medium text-muted-foreground italic py-8" id="time-slot-empty-state">
                            Select a provider to see available times.
                        </div>
                    </div>

                    <div id="day-unavailable-msg" class="hidden flex flex-col items-center justify-center p-8 text-center bg-destructive/10 rounded-2xl border border-destructive/20">
                        <span class="material-symbols-outlined text-destructive text-4xl mb-3">block</span>
                        <h4 class="text-base font-black text-destructive mb-1">Provider Unavailable</h4>
                        <p class="text-sm font-medium text-destructive/80">This specific day is not in the provider's active schedule.</p>
                    </div>
                </div>

                <!-- Provider Selection -->
                <div class="bg-card p-8 rounded-[2rem] border border-border shadow-sm">
                    <h3 class="text-xl font-black mb-6 flex items-center gap-3 text-foreground tracking-tight">
                        <span class="material-symbols-outlined text-primary text-3xl">person</span>
                        Assign Specialist
                    </h3>
                    <div class="relative">
                        <select
                            class="w-full h-14 rounded-xl border border-border bg-muted/30 px-5 text-foreground font-semibold focus:border-primary focus:ring-4 focus:ring-primary/10 outline-none transition-all duration-300 appearance-none"
                            id="doctor_uuid" name="doctor_uuid" required>
                            <option value="">Choosing an expert...</option>
                        </select>
                        <div
                            class="absolute right-6 top-1/2 -translate-y-1/2 pointer-events-none text-muted-foreground">
                            <span class="material-symbols-outlined text-2xl">expand_more</span>
                        </div>
                    </div>
                    <p
                        class="mt-4 text-[11px] font-bold text-muted-foreground leading-relaxed uppercase tracking-wider opacity-70">
                        Selecting a specific specialist may limit the available time slots above.
                    </p>
                </div>
            </div>
        </div>

        <div class="pt-8 border-t border-border flex flex-col sm:flex-row justify-between items-center gap-4">

            <a href="#" id="back-btn"
                class="inline-flex items-center gap-3 px-10 py-4 rounded-2xl font-black text-sm bg-muted text-foreground hover:bg-muted/80 transition-colors w-full sm:w-auto justify-center shadow-sm">
                <span class="material-symbols-outlined text-xl">arrow_back</span>
                Back to Service
            </a>

            <div id="reschedule-spacer" class="hidden sm:block hidden"></div>

            <button type="submit"
                class="inline-flex items-center justify-center gap-3 px-12 py-4 rounded-2xl font-black text-sm bg-primary text-white shadow-xl shadow-primary/25 hover:opacity-95 transform transition-all active:scale-[0.98] w-full sm:w-auto group">
                Review Appointment Details
                <span
                    class="material-symbols-outlined text-xl group-hover:translate-x-1 transition-transform">arrow_forward</span>
            </button>
        </div>
    </form>
</div>
<script>
    $(document).ready(function () {
        const $doctorSelect = $('#doctor_uuid');
        const $selectedDateInput = $('#selected-date');
        const $displaySelectedDate = $('#display-selected-date');
        const $calendarDays = $('#calendar-days');
        const $monthLabel = $('#calendar-month-label');
        const $form = $('#booking-form-step-2');
        const $backBtn = $('#back-btn');
        const $rescheduleSpacer = $('#reschedule-spacer');
        const $timeSlotsContainer = $('#time-slots-container');
        const $dayUnavailableMsg = $('#day-unavailable-msg');
        const $timeSlotEmptyState = $('#time-slot-empty-state');

        // Page Configurations from URL Params (CSR)
        const params = new URLSearchParams(window.location.search);
        const config = {
            service: params.get('service') || '',
            doctorUuid: params.get('doctor_uuid') || '',
            rescheduleUuid: params.get('reschedule_uuid') || '',
            editUuid: params.get('edit_uuid') || '',
            patientUuid: params.get('patient_uuid') || '',
            notes: params.get('notes') || '',
            date: params.get('date') || new Date().toISOString().split('T')[0],
            time: params.get('time') || ''
        };

        // State for Calendar Navigation
        let currentYear, currentMonth;
        let doctorAvailability = null;
        let allDoctorsData = []; // Store the doctors data locally

        // Initialize State
        $('input[name="service"]').val(config.service);
        $selectedDateInput.val(config.date);

        // Parse initial date for calendar view
        const initialDate = new Date(config.date);
        currentYear = initialDate.getFullYear();
        currentMonth = initialDate.getMonth(); // 0-indexed

        // Time selection logic moved to generateTimeSlots()

        // Initial Renders
        getDoctors();
        // Delay renderCalendar slightly so getDoctors can set availability if doctorUuid exists
        setTimeout(() => {
            renderCalendar(currentYear, currentMonth);
            updateDateDisplay(config.date);
            setupNavigation();
        }, 100);

        // --- Event Handlers ---

        $('#prev-month').on('click', function () {
            currentMonth--;
            if (currentMonth < 0) {
                currentMonth = 11;
                currentYear--;
            }
            renderCalendar(currentYear, currentMonth);
        });

        $('#next-month').on('click', function () {
            currentMonth++;
            if (currentMonth > 11) {
                currentMonth = 0;
                currentYear++;
            }
            renderCalendar(currentYear, currentMonth);
        });

        // Delegate event for dynamically created calendar days
        $calendarDays.on('click', '.calendar-day', function () {
            if ($(this).hasClass('opacity-30')) return; // Ignore disabled days

            const date = $(this).data('date');
            if (!date) return;

            // Update State
            config.date = date; // Update config state
            $selectedDateInput.val(date);

            // Visual Updates
            updateCalendarSelection(date);
            updateDateDisplay(date);
            generateTimeSlots(date);
        });

        $doctorSelect.on('change', function () {
            const selectedUuid = $(this).val();
            const doctor = allDoctorsData.find(d => d.uuid === selectedUuid);

            if (doctor && doctor.availability) {
                try {
                    doctorAvailability = typeof doctor.availability === 'string'
                        ? JSON.parse(doctor.availability)
                        : doctor.availability;
                } catch (e) {
                    doctorAvailability = null;
                }
            } else {
                doctorAvailability = null;
            }

            renderCalendar(currentYear, currentMonth);
            generateTimeSlots(config.date);
            
            // After initial hydration, clear the URL time so subsequent day-clicks default to the first slot
            config.time = '';
        });

        // --- Core Functions ---

        function renderCalendar(year, month) {
            $calendarDays.empty();

            const firstDayOfMonth = new Date(year, month, 1).getDay(); // 0 (Sun) - 6 (Sat)
            const daysInMonth = new Date(year, month + 1, 0).getDate();
            const today = new Date();
            today.setHours(0, 0, 0, 0);

            // Update Month Label
            const monthName = new Date(year, month).toLocaleString('en-US', { month: 'long', year: 'numeric' });
            $monthLabel.text(monthName);

            const daysOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];

            // Empty slots for days before the 1st
            for (let i = 0; i < firstDayOfMonth; i++) {
                $calendarDays.append('<div class="aspect-square"></div>');
            }

            // Generate Days
            for (let day = 1; day <= daysInMonth; day++) {
                const dateObj = new Date(year, month, day);
                const dayName = daysOfWeek[dateObj.getDay()];
                const dateString = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;

                const isPast = dateObj < today;
                const isSelected = dateString === config.date;

                // Check doctor availability
                let isAvailable = true;
                if (doctorAvailability && doctorAvailability[dayName]) {
                     isAvailable = (doctorAvailability[dayName].active == 1 || doctorAvailability[dayName].active === true || doctorAvailability[dayName].active === 'true');
                }

                let classes = 'calendar-day aspect-square flex flex-col items-center justify-center rounded-2xl transition-all text-sm font-black border cursor-pointer ';

                if (isPast || (doctorAvailability && !isAvailable)) {
                    classes += 'text-muted-foreground opacity-30 cursor-not-allowed border-transparent pointer-events-none';
                } else if (isSelected) {
                    classes += 'bg-primary text-white shadow-xl shadow-primary/30 border-transparent';
                } else {
                    classes += 'hover:bg-primary/10 hover:text-primary border-transparent';
                }

                const $btn = $(`<button type="button" data-date="${dateString}" class="${classes}">${day}</button>`);
                $calendarDays.append($btn);
            }
        }

        function updateCalendarSelection(selectedDate) {
            $('.calendar-day').each(function () {
                const dayDate = $(this).data('date');
                // Rely on the initial classes which set pointer-events-none for past and unavailable dates
                if ($(this).hasClass('pointer-events-none')) return;

                $(this).removeClass('bg-primary text-white shadow-xl shadow-primary/30 hover:bg-primary/10 hover:text-primary border-transparent');

                if (dayDate === selectedDate) {
                    $(this).addClass('bg-primary text-white shadow-xl shadow-primary/30 border-transparent');
                } else {
                    $(this).addClass('hover:bg-primary/10 hover:text-primary border-transparent');
                }
            });
        }

        function formatTime12Hour(timeStr) {
            const [hourStr, minStr] = timeStr.split(':');
            let hours = parseInt(hourStr, 10);
            const ampm = hours >= 12 ? 'PM' : 'AM';
            hours = hours % 12;
            hours = hours ? hours : 12;
            return `${hours}:${minStr} ${ampm}`;
        }

        function generateTimeSlots(dateString) {
            $timeSlotsContainer.addClass('hidden').empty();
            $dayUnavailableMsg.addClass('hidden');
            $timeSlotEmptyState.addClass('hidden');

            if (!doctorAvailability) {
                $timeSlotsContainer.removeClass('hidden').append($timeSlotEmptyState.removeClass('hidden'));
                return;
            }

            const dateObj = new Date(dateString);
            const daysOfWeek = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'];
            const dayName = daysOfWeek[dateObj.getDay()];

            const daySchedule = doctorAvailability[dayName];
            
            if (!daySchedule || daySchedule.active == 0 || daySchedule.active === false || daySchedule.active === 'false') {
                $dayUnavailableMsg.removeClass('hidden');
                return;
            }

            $timeSlotsContainer.removeClass('hidden');

            const startStr = daySchedule.start || '09:00';
            const endStr = daySchedule.end || '17:00';

            const startHour = parseInt(startStr.split(':')[0], 10);
            const endHour = parseInt(endStr.split(':')[0], 10);

            let slotsGenerated = 0;

            for (let hour = startHour; hour < endHour; hour++) {
                // Skip 12 PM (Break time)
                if (hour === 12) continue;

                const time24 = `${String(hour).padStart(2, '0')}:00`;
                const time12 = formatTime12Hour(time24);
                
                // Fuzzy match for pre-selection via URL config.time
                let isChecked = false;
                if (config.time) {
                    // Try to match the hour based on URL string
                    const dummyDate = '2000-01-01';
                    const targetDate = new Date(`${dummyDate} ${config.time}`);
                    if (!isNaN(targetDate.getTime()) && targetDate.getHours() === hour) {
                        isChecked = true;
                    } else if (config.time === time12 || config.time === time24) {
                        isChecked = true;
                    }
                } else if (slotsGenerated === 0) {
                     // Check first available if no config
                     isChecked = true;
                }

                const checkedAttr = isChecked ? 'checked' : '';
                
                const $label = $(`
                    <label class="cursor-pointer">
                        <input type="radio" name="time_slot" value="${time12}" class="peer absolute opacity-0" ${checkedAttr} />
                        <div class="py-4 px-4 text-sm font-black rounded-2xl border-2 border-transparent bg-muted/30 text-muted-foreground transition-all text-center peer-checked:border-primary peer-checked:bg-primary/5 peer-checked:text-primary hover:border-primary/30 hover:scale-[1.02] active:scale-[0.98]">
                            ${time12}
                        </div>
                    </label>
                `);
                
                $timeSlotsContainer.append($label);
                slotsGenerated++;
            }
            
            if (slotsGenerated === 0) {
                 $dayUnavailableMsg.removeClass('hidden');
                 $timeSlotsContainer.addClass('hidden');
            }
        }

        function updateDateDisplay(dateStr) {
            // Fix input if needed
            const dateObj = new Date(dateStr);
            // Handle invalid dates gracefully if manual entry
            if (isNaN(dateObj)) return;

            const formattedDate = dateObj.toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric'
            });
            $displaySelectedDate.text(formattedDate);

            // Sync calendar view if the selected date is not in the current view?
            // Optional: Auto-navigate to the month of the selected date. 
            // For now, let's keep them independent strictly or check if we want to jump.
            // If we want to jump:
            /*
            if (dateObj.getMonth() !== currentMonth || dateObj.getFullYear() !== currentYear) {
                currentMonth = dateObj.getMonth();
                currentYear = dateObj.getFullYear();
                renderCalendar(currentYear, currentMonth);
            }
            */
            // But since updateDateDisplay is called on init and on click, we don't need to re-render 
            // if it was triggered by a click inside the month. Only on init might be useful.
        }

        function getDoctors() {
            $.ajax({
                url: apiUrl("shared") + "doctors.php?service_uuid=" + encodeURIComponent(config.service),
                method: "GET",
                dataType: "json",
                success: function (response) {
                    if (!response.success) {
                        $doctorSelect.html('<option value="">Error loading doctors</option>');
                        return;
                    }

                    allDoctorsData = response.data; // Cache data
                    let html = '<option value="" disabled' + (!config.doctorUuid ? ' selected' : '') + '>Select a Provider</option>';
                    response.data.forEach(d => {
                        const selected = (d.uuid === config.doctorUuid) ? 'selected' : '';
                        html += `<option value="${d.uuid}" ${selected}>Dr. ${d.firstname} ${d.lastname}</option>`;
                    });
                    $doctorSelect.html(html);

                    if (config.doctorUuid) {
                        $doctorSelect.trigger('change');
                    }
                },
                error: function () {
                    $doctorSelect.html('<option value="">Failed to load providers</option>');
                }
            });
        }

        function setupNavigation() {
            // Back Button Logic
            if (config.rescheduleUuid) {
                // If rescheduling, hide back button and show spacer
                $backBtn.addClass('hidden');
                $rescheduleSpacer.removeClass('hidden');
            } else {
                const backParams = new URLSearchParams();
                if (config.service) backParams.append('service', config.service);
                if (config.doctorUuid) backParams.append('doctor_uuid', config.doctorUuid); // Maybe they selected a doctor in step 1?
                if (config.notes) backParams.append('notes', config.notes);
                if (config.editUuid) backParams.append('edit_uuid', config.editUuid);
                if (config.patientUuid) backParams.append('patient_uuid', config.patientUuid);
                if (config.date) backParams.append('date', config.date);
                if (config.time) backParams.append('time', config.time);

                $backBtn.attr('href', `step-1-service.php?${backParams.toString()}`);
            }
        }

        // Keep back-nav URL in sync when picking specific dates and times
        $calendarDays.on('click', '.calendar-day', function () {
             setupNavigation(); // ensure `config.date` from state updates back param
        });

        $timeSlotsContainer.on('change', 'input[name="time_slot"]', function() {
              config.time = $(this).val(); // update the local state with the exact radio chosen
              setupNavigation();
        });

        // Manual Navigation Handler
        $form.on('submit', function (e) {
            e.preventDefault();

            const doctorUuid = $doctorSelect.val();
            const service = $('input[name="service"]').val();
            const date = $selectedDateInput.val();
            const timeSlot = $('input[name="time_slot"]:checked').val();

            if (!doctorUuid) {
                alert('Please select a provider before continuing.');
                return false;
            }

            if (!date || !timeSlot) {
                alert('Please select a date and time.');
                return false;
            }

            const nextParams = new URLSearchParams();
            nextParams.append('service', service);
            nextParams.append('doctor_uuid', doctorUuid);
            nextParams.append('date', date);
            nextParams.append('time_slot', timeSlot);

            if (config.rescheduleUuid) nextParams.append('reschedule_uuid', config.rescheduleUuid);
            if (config.editUuid) nextParams.append('edit_uuid', config.editUuid);
            if (config.patientUuid) nextParams.append('patient_uuid', config.patientUuid);
            if (config.notes) nextParams.append('notes', config.notes);

            window.location.href = `step-3-review.php?${nextParams.toString()}`;
            return false;
        });
    });
</script>