<?php
/**
 * Category Modal
 * 
 * Modal for creating and editing service categories.
 */
?>
<!-- Modal Overlay -->
<div id="category-modal" class="fixed inset-0 z-[100] flex items-center justify-center p-4 modal-overlay hidden">
    <!-- Backdrop -->
    <div class="absolute inset-0 bg-black/50 backdrop-blur-sm transition-opacity opacity-0"
        id="category-modal-backdrop"></div>

    <!-- Modal Content -->
    <div class="bg-card dark:bg-card w-full max-w-xl rounded-xl shadow-2xl overflow-hidden flex flex-col max-h-[95vh] relative z-10 transform scale-95 opacity-0 transition-all duration-300"
        id="category-modal-panel">

        <!-- Header -->
        <div class="px-8 py-6 border-b border-border flex justify-between items-center bg-card sticky top-0 z-10">
            <div>
                <h3 class="text-xl font-bold text-foreground" id="category-modal-title">Add New Category</h3>
                <p class="text-xs text-muted-foreground font-medium mt-1 uppercase tracking-wider"
                    id="category-modal-subtitle">
                    Organize your services</p>
            </div>
            <button type="button"
                class="text-muted-foreground hover:text-foreground transition-colors category-modal-close">
                <span class="material-symbols-outlined">close</span>
            </button>
        </div>

        <!-- Scrollable Body -->
        <div class="flex-1 overflow-y-auto p-8">
            <form id="category-form" class="space-y-6">
                <!-- Category Name -->
                <div class="space-y-2">
                    <label class="block text-[11px] font-bold text-muted-foreground uppercase tracking-wider mb-1.5"
                        for="category-name">Category Name</label>
                    <input
                        class="w-full bg-muted/50 border border-border rounded-lg py-2 px-3 text-sm focus:ring-primary focus:border-primary transition-all"
                        id="category-name" name="name" placeholder="e.g., Therapy" type="text" />
                </div>

                <!-- Icon Selection -->
                <div class="space-y-3">
                    <label
                        class="block text-[11px] font-bold text-muted-foreground uppercase tracking-wider mb-1.5">Select
                        Category Icon</label>
                    <div class="grid grid-cols-6 sm:grid-cols-8 gap-3" id="icon-grid">
                        <!-- Icons will be generated by JS or static list -->
                        <?php
                        $icons = [
                            'psychology',
                            'clinical_notes',
                            'medical_services',
                            'groups',
                            'local_hospital',
                            'monitor_heart',
                            'medication',
                            'health_and_safety',
                            'biotech',
                            'family_restroom',
                            'emergency',
                            'healing'
                        ];
                        foreach ($icons as $icon): ?>
                            <button type="button"
                                class="aspect-square flex items-center justify-center rounded-xl border border-border hover:border-primary hover:text-primary transition-all text-muted-foreground icon-select-btn"
                                data-icon="<?= $icon ?>">
                                <span class="material-symbols-outlined text-xl"><?= $icon ?></span>
                            </button>
                        <?php endforeach; ?>
                        <input type="hidden" name="icon" id="category-icon" value="">
                    </div>
                </div>

                <!-- Description -->
                <div class="space-y-2">
                    <label class="block text-[11px] font-bold text-muted-foreground uppercase tracking-wider mb-1.5"
                        for="category-desc">Description</label>
                    <textarea
                        class="w-full bg-muted/50 border border-border rounded-lg py-2 px-3 text-sm focus:ring-primary focus:border-primary transition-all resize-none"
                        id="category-desc" name="description"
                        placeholder="Enter a brief description of this category..." rows="4"></textarea>
                </div>

                <!-- Status & ID -->
                <input type="hidden" name="id" id="category-id">
                <div class="flex items-center gap-3">
                    <label class="text-[11px] font-bold text-muted-foreground uppercase tracking-wider"
                        for="category-status">Status</label>
                    <select id="category-status" name="status"
                        class="bg-muted/50 border border-border rounded-lg py-1 px-2 text-sm focus:ring-primary focus:border-primary">
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                </div>
            </form>
        </div>

        <!-- Footer -->
        <div class="px-8 py-6 border-t border-border flex justify-end gap-3 bg-card sticky bottom-0 z-10">
            <button type="button"
                class="px-6 py-2.5 text-sm font-bold text-muted-foreground hover:text-foreground transition-all category-modal-close">
                Cancel
            </button>
            <button type="submit" form="category-form"
                class="px-8 py-2.5 bg-primary text-primary-foreground rounded-lg text-sm font-bold hover:opacity-90 transition-all shadow-lg shadow-primary/25">
                Save Category
            </button>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        const $modal = $('#category-modal');
        const $backdrop = $('#category-modal-backdrop');
        const $panel = $('#category-modal-panel');
        const $form = $('#category-form');

        // Open Modal Function
        window.openCategoryModal = function (mode = 'add', data = null) {
            $modal.removeClass('hidden');
            // Small delay to allow display flex to apply before opacity transition
            setTimeout(() => {
                $backdrop.removeClass('opacity-0');
                $panel.removeClass('scale-95 opacity-0');
            }, 10);

            if (mode === 'edit' && data) {
                $('#category-modal-title').text('Edit Category');
                $('#category-name').val(data.name);
                $('#category-desc').val(data.desc);
                // Select icon logic
                $('.icon-select-btn').removeClass('border-2 border-primary bg-primary/5 text-primary').addClass('border-border text-muted-foreground');
                if (data.icon) {
                    $(`.icon-select-btn[data-icon="${data.icon}"]`).addClass('border-2 border-primary bg-primary/5 text-primary').removeClass('border-border text-muted-foreground');
                    $('#category-icon').val(data.icon);
                }
            } else {
                $('#category-modal-title').text('Add New Category');
                $form[0].reset();
                $('#category-id').val('');
                $('.icon-select-btn').removeClass('border-2 border-primary bg-primary/5 text-primary').addClass('border-border text-muted-foreground');
                $('#category-icon').val('');
            }
        };

        // Close Modal Function
        window.closeCategoryModal = function () {
            $backdrop.addClass('opacity-0');
            $panel.addClass('scale-95 opacity-0');
            setTimeout(() => {
                $modal.addClass('hidden');
            }, 300);
        };

        // Close events
        $('.category-modal-close').on('click', closeCategoryModal);
        $modal.on('click', function (e) {
            if ($(e.target).is($modal)) closeCategoryModal();
        });

        // Icon Selection
        $('.icon-select-btn').on('click', function () {
            $('.icon-select-btn').removeClass('border-2 border-primary bg-primary/5 text-primary').addClass('border-border text-muted-foreground');
            $(this).removeClass('border-border text-muted-foreground').addClass('border-2 border-primary bg-primary/5 text-primary');
            $('#category-icon').val($(this).data('icon'));
        });

        // Category Submit
        $form.on('submit', function (e) {
            e.preventDefault();
            const formData = new FormData(this);
            const id = $('#category-id').val();
            formData.append('action', id ? 'update' : 'store');

            // console.log('frontend:', formData);
            // return false;

            $.ajax({
                url: apiUrl('shared') + 'categories.php',
                method: 'POST',
                data: formData,
                headers: { 'X-Reference-Model': 'services' },
                processData: false,
                contentType: false,
                success: function (response) {
                    // console.log('backend:', response);
                    // return false;
                    if (!response.success) return false;
                    alert(response.message);
                    window.closeCategoryModal();
                    $(document).trigger('category-saved');
                },
                error: ajaxErrorHandler
            });
        });
    });
</script>